# Generated by Django 2.2.14 on 2020-08-01 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200731_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('ISBN', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('sets', models.SmallIntegerField(default=1)),
                ('age_group', models.CharField(max_length=8, null=True)),
                ('publisher', models.CharField(max_length=50, null=True)),
                ('parent_cate', models.CharField(max_length=10, null=True)),
                ('sub_cate', models.CharField(max_length=10, null=True)),
                ('book_size', models.CharField(max_length=4, null=True)),
                ('language', models.CharField(max_length=6, null=True)),
                ('ori_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField()),
                ('ori_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cut_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('plus_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prom', models.CharField(max_length=10)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListenList',
            fields=[
                ('product_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentPrice',
            fields=[
                ('historyprice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.HistoryPrice')),
                ('pre_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bot_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            bases=('books.historyprice',),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('ISBN', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('total', models.SmallIntegerField()),
                ('placed', models.SmallIntegerField()),
                ('placed_on', models.CharField(max_length=4)),
                ('stocked', models.SmallIntegerField()),
                ('stocked_on', models.CharField(max_length=4)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
        migrations.AddField(
            model_name='historyprice',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.ListenList'),
        ),
    ]
