# Generated by Django 2.2.14 on 2020-08-01 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200801_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyprice',
            name='detail',
        ),
        migrations.DeleteModel(
            name='CurrentPrice',
        ),
        migrations.DeleteModel(
            name='HistoryPrice',
        ),
        migrations.DeleteModel(
            name='ListenList',
        ),
    ]
