# Generated by Django 2.2.14 on 2020-08-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_currentprice_historyprice_listenlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentprice',
            name='final_discount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
    ]
