# Generated by Django 2.2.14 on 2020-08-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_currentprice_final_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentprice',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
