# Generated by Django 2.2.14 on 2020-08-01 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_currentprice_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentprice',
            name='bot_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='currentprice',
            name='pre_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='PrePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField()),
                ('ori_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cut_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('plus_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prom', models.CharField(max_length=10)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.ListenList')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
