# Generated by Django 2.2.14 on 2020-08-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20200801_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentprice',
            name='created_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historyprice',
            name='created_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='preprice',
            name='created_time',
            field=models.DateTimeField(),
        ),
    ]
