# Generated by Django 2.2.14 on 2020-08-04 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20200804_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('return_time', models.DateTimeField(null=True)),
                ('borrow_memo', models.CharField(max_length=50, null=True)),
                ('return_memo', models.CharField(max_length=50, null=True)),
                ('ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Stock')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.MemberState')),
            ],
        ),
    ]
