# Generated by Django 2.2.14 on 2020-08-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_borrowrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowrecord',
            old_name='ISBN',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='borrowrecord',
            old_name='member_id',
            new_name='member',
        ),
    ]
