# Generated by Django 2.2.14 on 2020-08-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_auto_20200806_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
