# Generated by Django 2.2.14 on 2020-08-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20200806_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_size',
        ),
        migrations.RemoveField(
            model_name='book',
            name='parent_cate',
        ),
        migrations.RemoveField(
            model_name='book',
            name='sub_cate',
        ),
        migrations.AddField(
            model_name='stock',
            name='book_size',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='parent_cate',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='sub_cate',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
