# Generated by Django 2.2.14 on 2020-08-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_auto_20200806_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='placed',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='placed_on',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stocked',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stocked_on',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='total',
            field=models.SmallIntegerField(null=True),
        ),
    ]
