# Generated by Django 2.2.14 on 2020-08-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_auto_20200806_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='placed',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stocked',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='total',
            field=models.SmallIntegerField(default=0),
        ),
    ]
