# Generated by Django 2.2.14 on 2020-08-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_auto_20200806_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField()),
                ('channel', models.CharField(default='京东', max_length=10)),
                ('total_price_sale', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prom_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('coupon_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_price_paid', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=16)),
                ('package_id', models.CharField(max_length=16)),
                ('price_sale', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_sold', models.BooleanField(default=0)),
                ('is_package', models.BooleanField(default=0)),
                ('memo', models.CharField(max_length=20)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
