# Generated by Django 2.2.14 on 2020-08-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_purchasebatch_purchasedetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseDetail',
        ),
        migrations.AlterField(
            model_name='purchasebatch',
            name='discount',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
    ]
