# Generated by Django 2.2.14 on 2020-08-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_purchasebatch_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedetail',
            name='is_package',
        ),
        migrations.AddField(
            model_name='book',
            name='is_package',
            field=models.BooleanField(default=0),
        ),
    ]
