# Generated by Django 2.2.14 on 2020-08-08 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_auto_20200808_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='books.PurchaseDetail')),
                ('member', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='books.MemberState')),
            ],
        ),
    ]
