# Generated by Django 2.2.14 on 2020-08-08 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0032_auto_20200808_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('actually_paid', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='books.PurchaseDetail')),
            ],
        ),
    ]
