# Generated by Django 2.2.14 on 2020-08-08 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0033_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='member',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='books.MemberState'),
        ),
    ]
