# Generated by Django 2.2.14 on 2020-08-11 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0037_auto_20200811_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedetail',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='book',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='PurchaseDetail',
        ),
    ]
