# Generated by Django 2.2.14 on 2020-08-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0039_order_purchasedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchasebatch',
            name='created_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='created_time',
            field=models.DateTimeField(),
        ),
    ]
