# Generated by Django 2.2.14 on 2020-08-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0040_auto_20200812_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebatch',
            name='coupon_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='purchasebatch',
            name='prom_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='purchasebatch',
            name='total_price_paid',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='purchasebatch',
            name='total_price_sale',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
