# Generated by Django 2.2.14 on 2020-08-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0044_auto_20200812_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='damaged',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
