# Generated by Django 2.2.14 on 2020-08-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0045_borrowrecord_damaged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='created_time',
            field=models.DateTimeField(),
        ),
    ]
