# Generated by Django 2.2.14 on 2020-08-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0046_auto_20200812_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
