# Generated by Django 2.2.14 on 2020-08-12 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0048_auto_20200812_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='MemberLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('begin_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('deposit', models.SmallIntegerField(null=True)),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.MemberState')),
            ],
        ),
    ]
