# Generated by Django 2.2.14 on 2020-08-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0049_auto_20200812_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberlog',
            old_name='member_id',
            new_name='member',
        ),
        migrations.AddField(
            model_name='memberlog',
            name='cart_id',
            field=models.IntegerField(null=True),
        ),
    ]
