# Generated by Django 2.2.14 on 2020-08-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0050_auto_20200812_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberlog',
            name='paid_by',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
