# Generated by Django 2.2.14 on 2020-08-14 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0052_packagemap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagemap',
            old_name='ISBN',
            new_name='book',
        ),
        migrations.AlterUniqueTogether(
            name='packagemap',
            unique_together={('package_id', 'book')},
        ),
    ]
