# Generated by Django 2.2.14 on 2020-08-15 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0053_auto_20200814_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='books.PurchaseDetail'),
        ),
    ]
